# Javascript Node.js CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  cicd: eqtpartners/cicd@2.0.17

workflows:
  build_and_deploy:
    jobs:
      - cicd/buildimage:
          context: gophish-test
          dockerfile: Dockerfile
          dockertag: image
          filters:
            branches:
              only: master
          buildtest: false
      - cicd/snykscan:
          context: gophish-test
          filters:
            branches:
              only: master
          requires:
            - cicd/buildimage
