# Javascript Node.js CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  gcp:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine

commands:
  build_and_push_image:
    parameters:
      imageProjectId:
        type: string
      tagNumber:
        type: string

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Authenticate to GCP
          command: |
            source ./pipeline-scripts.sh
            gcpAuthenticate ${GOOGLE_AUTH} << parameters.imageProjectId >> ${COMPUTE_ZONE}
            gcloud auth configure-docker

      - run:
          name: Install tools
          command: |
            source ./pipeline-scripts.sh
            download_and_install_kustomize

      - run:
          name: Build and push application container image
          command: |
            serverImageTag="europe-west1-docker.pkg.dev/<< parameters.imageProjectId >>/${APP_NAME}-repository/${APP_NAME}-image:<< parameters.tagNumber >>"
            docker build -t ${serverImageTag} --file Dockerfile .
            docker push ${serverImageTag}



jobs:
  build_and_push_image:
    executor: gcp
    steps:
      - build_and_push_image:
          imageProjectId: "eqt-cicd-prod"
          tagNumber: "5"

workflows:
  version: 2.1
  build_and_push_image:
    jobs:
      - build_and_push_image:
          context: i9n-commons
          filters:
            branches:
              only: master
