version: 2.1
orbs:
  cicd: eqtpartners/cicd@5

workflows:
  build_and_deploy:
    jobs:
      - cicd/buildimage:
          context: gophish
          dockerfile: Dockerfile
          dockertag: image
          filters:
            branches:
              only: master
          buildtest: false
